# Generated by Django 2.2.5 on 2020-05-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_mark', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_students',
            },
        ),
    ]
